version: '3.9'

services:
  nginx:
    image: nginx:1.27.2
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
    ports:
      - "80:80"
    networks:
      - adc-network
  identity:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: identity
    command: 'start-dev --import-realm'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HTTP_PORT: 80
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./identity/themes/uithemes:/opt/keycloak/themes
    networks:
      - adc-network
  storefront:
    build: ./storefrontbff
    container_name: storefrontbff
    image: adc/storefront-bff:latest
    entrypoint: ["./wait-for-it.sh", "identity:80", "--timeout=300", "--", "java", "-jar", "/app.jar"]
    environment:
      - SERVER_PORT
      - ADC_SERVICES_CUSTOMER
      - ADC_SERVICES_ORDER
    networks:
      - adc-network
#  storefront-nextjs:
#    build: ./storefront
#    image: adc/storefront:latest
#    networks:
#      - adc-network
  postgres:
    image: postgres:16-alpine
    hostname: ${POSTGRES_HOST}
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./docker/postgres/postgresql.conf:/usr/share/postgresql/postgresql.conf
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - adc-network

  pgadmin:
    image: dpage/pgadmin4:6.14
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@adc.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - adc-network
#  product:
#    build: ./product
#    container_name: product
#    image: adc/product:latest
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book
#      - SERVER_SERVLET_CONTEXT_PATH=/product
#      - SERVER_PORT
#    networks:
#      - adc-network
#
#  customer:
#    container_name: customer
#    build: ./customer
#    image: adc/customer:latest
#    environment:
#      - SPRING_DATASOURCE_URL= jdbc:postgresql://postgres:5432/customer
#      - SERVER_SERVLET_CONTEXT_PATH= /customer
#      - SERVER_PORT
#    networks:
#      - adc-network
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.14
    environment:
      - BASE_URL=/swagger-ui
      - URLS
      - OAUTH_CLIENT_ID=swagger-ui
      - OAUTH_USE_PKCE=true
    networks:
      - adc-network

networks:
  adc-network:
    driver: bridge
    name: adc-network

volumes:
  postgres:
  pgadmin:
