version: '3.9'

services:
  gatewayserver:
    build:
      context: ./gatewayserver
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - book-network
  identity:
    image: quay.io/keycloak/keycloak:26.0.2
    command: 'start-dev --import-realm'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - book-network

  postgres:
    image: postgres:16-alpine
    hostname: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/postgresql.conf:/usr/share/postgresql/postgresql.conf
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - book-network

  pgadmin:
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@adc.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - book-network
    volumes:
      - pgadmin:/var/lib/pgadmin
  book:
    build:
      context: ./book
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customer
    networks:
      - book-network

  customer:
    build:
      context: ./customer
    ports:
      - "8090:8090"
    environment:
       SPRING_PROFILES_ACTIVE: prod
       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer
    networks:
      - book-network


networks:
  book-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
