server:
  port: 8087
spring:
  application:
    name: storefront
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Identity
        registration:
          keycloak:
            provider: keycloak
            client-id: storefront-bff
            client-secret: rNlTPrKe7WqDqJY6hU5ueJb8BCr3QDYj
            scope: openid, profile, email, roles
---
spring:
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://nginx
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Origin Access-Control-Request-Method Access-Control-Request-Headers
            - TokenRelay=
            - StripPrefix=1
#        - id: nextjs
#          uri: http://storefront-nextjs:3000
#          predicates:
#            - Path/**
---
adc:
  services:
    token-identity: http://localhost:8080/realms/Identity/protocol/openid-connect/token