backend:
  image:
    repository: ghcr.io/?/yas-{{service}}
    tag: latest

  nameOverride: {{service}}
  fullnameOverride: {{service}}
  databaseName: {{service}}

  ingress:
    enabled: true
    host: api.?
    path: /{{service}}