#Configmap all microservices
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  application.yaml: |
      {{- toYaml .Values.applicationConfig | nindent 4 }}
---

---
#Configmap for customer application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  customer-application.yaml: |
    {{ toYaml .Values.customerApplicationConfig | nindent 4 }}
---
# Configmap of production application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: book-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  book-application.yaml: |
    {{ toYaml .Values.bookApplicationConfig | nindent 4 }}
