server:
  port: 8087
spring:
  application:
    name: storefront
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity/realms/Identity
        registration:
          keycloak:
            provider: keycloak
            client-id: storefront-bff
            client-secret: ZrU9I0q2uXBglBnmvyJdkl1lf0ncr8tn
            scope: openid, profile, email, roles
---
spring:
  cloud:
    gateway:
      routes: 
        - id: api
          uri: http://nginx
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Origin Access-Control-Request-Method Access-Control-Request-Headers
            - TokenRelay=
            - StripPrefix=1
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
---
adc:
  services:
    token-identity: http://identity/realms/Identity/protocol/openid-connect/token