server:
  port: 8087
spring:
  application:
    name: storefront-bff
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity/realms/Identity
        registration:
          keycloak:
            provider: keycloak
            client-id: storefront-bff
            client-secret: ZrU9I0q2uXBglBnmvyJdkl1lf0ncr8tn
            scope: openid, profile, email, roles
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
---
spring:
  cloud:
    gateway:
      routes:
        - id: api_product_local
          uri: http://localhost:8080
          predicates:
            - Path=/api/product/**
          filters:
            - TokenRelay=
            - StripPrefix=1
        - id: api_order_local
          uri: http://localhost:8085
          predicates:
            - Path=/api/orders/**
          filters:
            - TokenRelay=
            - StripPrefix=1
        - id: api
          uri: http://api.adc.local
          predicates:
              - Path=/api/**
          filters:
              - TokenRelay=
              - StripPrefix=1
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
      default-filters:
        - SaveSession
---
adc:
  services:
    token-identity: http://identity/realms/Identity/protocol/openid-connect/token